service: api-failover-example
provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  environment:
    NODE_ENV: ${opt:stage}

functions:
  sendEmail:
    handler: dist/send.handler
    environment:
      MAILGUN_APIKEY: ${file(./config.json):${opt:stage}.mailgun.apiKey}
      MAILGUN_DOMAIN: ${file(./config.json):${opt:stage}.mailgun.domain}
      MAILGUN_SENDER: ${file(./config.json):${opt:stage}.mailgun.sender}
      SENDGRID_APIKEY: ${file(./config.json):${opt:stage}.sendgrid.apiKey}
      SENDGRID_SENDER: ${file(./config.json):${opt:stage}.sendgrid.sender}
    events:
      - http:
          path: api/email/send
          method: post
          cors: true

resources:
  Resources:
    DefaultGatewayResponse4XXError:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        RestApiId:
          Ref: "ApiGatewayRestApi"
        ResponseType: DEFAULT_4XX
        ResponseTemplates:
          application/json: '{ "error":{ "errors": [{"code":"$context.error.responseType","message":$context.error.messageString}], "message": ""}}'
    DefaultGatewayResponse5XXError:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        RestApiId:
          Ref: "ApiGatewayRestApi"
        ResponseType: DEFAULT_5XX
        ResponseTemplates:
          application/json: '{ "error":{ "errors": [{"code":"$context.error.responseType","message":$context.error.messageString}], "message": ""}}'
